[env]
TERM = "xterm-256color"

[window]
decorations = "Transparent"
blur = true
opacity = 0.7

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 10
y = 22

[font]
size = 14.0

[font.bold]
family = "Cascadia Mono"
style = "Bold"

[font.bold_italic]
family = "Cascadia Mono"
style = "Bold Italic"

[font.italic]
family = "Cascadia Mono"
style = "Italic"

[font.normal]
family = "Cascadia Mono"
style = "Regular"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [{ key = "C", mods = "Control", action = "Copy" },
            { key = "V", mods = "Control", action = "Paste" },
            { key = "Z", mods = "Control", chars = "\u0003"}]
